api/api/urls.py
from django.contrib import admin
from django.urls import path
# from api import views
from rest_framework_simplejwt.views import TokenRefreshView
from .views import home, create_post, post_detail, delete_post
from django.views.generic import TemplateView

app_name = 'api'

urlpatterns = [
    
    path('', home, name="home"),
    path('createpost/<str:pk>', create_post, name='create_post'),
    path('deletepost/<str:pk>/', delete_post, name="delete_post"),
    path("post/<str:pk>", post_detail, name="post_detail"),

]

api/placard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path("admin/", admin.site.urls),

    # path("auth/", include("rest_framework.urls")),
    
    path('user/', include('users.urls', namespace='user')),

    path('api/', include('api.urls', namespace='api')),
]

api/users/urls.py
from django.urls import path
from .views import register_view, user_profile
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from .forms import LoginForm

app_name = 'users'

urlpatterns = [

	path('register/', register_view, name="register"),
	path("logout/", auth_views.LogoutView.as_view(next_page="/user/login/"), name="logout"),
	    path(
        "login/",
        auth_views.LoginView.as_view(template_name="Login.html", next_page="/api/", form_class=LoginForm),
        name="login",
    ),
    path('user_profile/', user_profile, name="user_profile")

]

api/api/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext_lazy
from django.utils.text import slugify
from django.contrib.humanize.templatetags import humanize
# from googletrans import Translator
# from google_trans_new import google_translator


def upload_to(instance, filename):
    return 'posts/{filename}'.format(filename=filename)


class Post(models.Model):

    class PostObjects(models.Manager):
        def get_queryset(self):
            return super().get_queryset()

    STATUS_CHOICES = [
        ('A', 'نو'),
        ('B', 'در حد نو'),
        ('C', 'کارکرده'),
    ]

    TYPE_CHOICES = [
        ('Sell', 'خرید و فروش'),
        ('StudyBuddy', 'تیم سازی '),
    ]

    title = models.CharField(max_length=50)
    post_type = models.CharField(
        max_length=20, choices=TYPE_CHOICES, default='Sell')
    # status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='A')
    price = models.IntegerField(default=0)
    description = models.TextField(max_length=200, null=True, blank=True)
    contact_info = models.CharField(max_length=30)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    image = models.ImageField(
        gettext_lazy("Image"), upload_to=upload_to, default='media/nopicture.png', null=True)
    slug = models.SlugField(max_length=50, blank=True)
    date_created = models.DateTimeField(default=timezone.now)

    objects = models.Manager()  # default manager
    postobjects = PostObjects()  # custom manager

    class Meta:
        ordering = ('-date_created',)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_date(self):
        # translator = Translator(service_urls=['translate.googleapis.com'])
        # date = humanize.naturaltime(self.date_created)
        # date_fa = translator.translate(date, dest='fa', src='en').text()
        # return date_fa

        # translator = google_translator()
        # date = humanize.naturaltime(self.date_created)
        # date_fa = translator.translate(date, lang_src='en', lang_tgt='fa')
        # return date_fa
        return humanize.naturaltime(self.date_created)

    def get_price(self):
        return humanize.intcomma(self.price)

api/templates/CreatePost.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="{% static '/css/CreatePost.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@200&display=swap" rel="stylesheet">
  </head>
  <header>
    <!-- {/* the logo in header */} -->
    <div class="header-logo">
      <a href="{% url 'api:home' %}">
        <img class = "logo-img" src="{% static 'media/PlacardLogo.svg' %}" alt="Placard Logo" />
      </a>  
    </div>
  </header>
  
  <body>

      <div>
          <div class="CreatePost-form">
            <form class="CreatePost-form" method="POST" action="{% url 'api:create_post' user.id %}">
              {% csrf_token %}

              <h2>ثبت آگهی</h2>
              <label id="title">عنوان آگهی</label>                       
              {{create_post_form.title}}

              <label id="contact_info">راه ارتباطی</label>
              {{create_post_form.contact_info}}

              <label id="price">قیمت (به تومان)</label>
              <h5>* درصورت انتخاب گزینه "تیم سازی" از این بخش عبور کنید *</h5>
              {{create_post_form.price}}

              <label id="description">توضیحات</label>
              {{create_post_form.description}}

              <label id="quality">نوع آگهی</label>
              <label class="quality-form">
                <select name="post_type">
                  {% for choice in create_post_form.post_type %}
                  <option value={{choice.data.value}}>{{ choice.choice_label }}</option>
                  {% endfor %}
                </select>
              </label>

              <button id = "btn" type="submit">ثبت آگهی</button>

            </form>
          </div>
      </div>

    </body>

</html>

api/templates/Home.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="{% static '/css/Home.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@200&display=swap" rel="stylesheet">
  </head>
  <header>
    <!-- {/* the logo in header */} -->
    <div class="header_items">

    <!-- Placard logo from media folder -->
      <a href="{% url 'api:home' %}">
        <img class = "logo-img" src="{% static 'media/PlacardLogo.svg' %}" alt="Placard Logo" />
      </a>

      <!-- Buttons and links to other pages from home page -->
      <button id="create_post_btn" onclick=""><a href="{% url 'api:create_post' user.id %}">ثبت آگهی</a></button>
     
      <button id="header-profile-btn" onclick="">
        <h4>پلاکارد من</h4>
        <img src="{% static 'media/ProfilePic.png' %}" class="header-profilepic"/>
        <div class="sub-menu-wrap">
          <div class="sub-menu">
            <ul>
              <li>
                <h3>{{user.username}}</h3>
                <hr>
              </li>
              <li>
                <a href="{% url 'user:user_profile' %}" class="sub-menu-link">
                  <img src="{% static 'media/account.png' %}"/>
                  <p>پروفایل</p>
                </a>
              </li>
              <li>
                <a href="{% url 'user:logout' %}" class="sub-menu-link">
                  <img src="{% static 'media/logout.png' %}" />
                  <p>خروج</p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </button>
     </div>  

    </div>
    <br>
    <br>
  </header>
    <body>
      <!-- post appearance -->
      <div class="post-container">
        {% for post in posts %}
          {% if post.post_type == 'StudyBuddy' %}
            <div class="post-design-sb">
              <div class="post-info">
                <div class="post-info-h4">
                  <h4>
                    {% if post.price == 0 %}
                      رایگان
                    {% else %}
                      {{post.get_price}} تومان 
                    {% endif %}
                  </h4>
                  <h4>{{post.get_date}}</h4>
                </div>
                <a id="title" href="{% url 'api:post_detail' post.id %}"> {{post.title|truncatechars:14}} </a>
              </div>
              <div class="post-img">
                <img src="{% static 'media/nopicture.png' %}" alt="post picture"/>
              </div>
            </div>
          {% else %}
            <div class="post-design">
              <div class="post-info">
                <div class="post-info-h4">
                  <h4>{{post.get_date}}</h4>
                </div>
                <a id="title" href="{% url 'api:post_detail' post.id %}"> {{post.title|truncatechars:14}} </a>
              </div>
              <div class="post-img">
                <img src="{% static 'media/nopicture.png' %}" alt="post picture"/>
              </div>
            </div>
          {% endif %}
        
        {% if forloop.counter|divisibleby:"3" %}
          <br />
        {% endif %}

        {% endfor %}
      </div>

    </body>

</html>

api/templates/Login.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="{% static '/css/Login.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@200&display=swap" rel="stylesheet">
  </head>
  <header>
    <!-- {/* the logo in header */} -->
    <div class="header-logo">
      <svg width="64" height="64" viewBox="0 0 87 87" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M1 1H86V44.9651H1V1Z" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linejoin="round"/>
      <path d="M39.5018 45.1752H47.4735V85.9999H39.5018V45.1752Z" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linejoin="round"/>
      <path d="M8.1301 7.92542H78.8969V38.1984H8.1301V7.92542Z" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linejoin="round"/>
      <path d="M78.4718 26.5582H66.2081" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M66.1492 8.18945V37.6538" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M53.7675 8.56104L53.8855 37.3885L53.7675 8.56104Z" fill="black"/>
      <path d="M53.7675 8.56104L53.8855 37.3885" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M45.2423 15.6947L45.3329 34.0473" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M45.2423 19.5375L45.3329 37.8903" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M45.3045 15.3934L65.7139 8.43066" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M33.6309 15.9613L33.9059 37.4211" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M26.679 23.5443L26.7706 38.0709" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M29.1472 38.1964H20.7109" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M12.6756 26.7872H20.6393" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M12.4528 34.4675H20.6152" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M20.6442 26.8104V34.4716" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M70.123 30.3558L74.2544 30.356L70.123 30.3558Z" fill="black"/>
      <path d="M70.123 30.3558L74.2544 30.356" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      <path d="M72.3229 32.8382L72.3228 32.8381" stroke="black" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </div>
  </header>
  <body>
      <!-- {/* the svg designs */} -->
      <div>
        <div class="light-blub">
            <svg width="384" height="206" viewBox="0 0 384 206" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M204.731 1.2171C268.802 7.03621 329.998 42.3149 363.703 97.0908C395.981 149.547 380.945 213.504 372.923 274.556C364.313 340.089 372.901 422.332 316.448 456.747C260.437 490.893 195.001 432.928 130.219 422.516C63.324 411.764 -22.9651 449.99 -63.4555 395.688C-103.928 341.411 -54.9158 266.921 -33.7384 202.632C-16.8686 151.42 3.25533 102.895 44.4566 68.0957C90.4245 29.2705 144.789 -4.22708 204.731 1.2171Z" fill="#E3E8C0"/>
            </svg>
        </div>
        <div class="green-blub">
            <svg width="672" height="667" viewBox="0 0 672 667" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M960.756 293.016C998.781 397.683 917.42 498.262 896.31 607.475C877.655 703.987 921.359 823.693 846.011 886.659C770.018 950.163 658.929 883 559.974 888.536C412.267 896.799 253.314 1015.31 134.769 926.447C11.0027 833.667 -35.7687 631.333 31.4075 492.3C94.9422 360.803 305.378 421.55 421.471 333.065C536.755 245.197 531.327 11.7556 675.986 1.01276C816.702 -9.43728 912.504 160.198 960.756 293.016Z" fill="#008080"/>
            </svg>
        </div>
        <div class="orange-blub">
          <svg width="511" height="335" viewBox="0 0 511 335" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M-27.1815 -293.202C39.9494 -320.198 106.582 -347.538 176.003 -351.922C252.071 -356.726 329.771 -352.802 385.83 -319.283C443.717 -284.671 470.532 -225.511 488.043 -165.345C506.207 -102.937 527.628 -33.4741 487.983 31.7038C448.905 95.9482 352.564 118.771 285.853 167.063C219.43 215.145 175.796 287.741 97.0943 314.66C13.4756 343.261 -75.1559 337.905 -149.945 316.124C-226.024 293.967 -303.719 257.493 -324.565 191.859C-344.889 127.872 -274.023 55.4749 -255.177 -15.1977C-239.15 -75.3 -266.431 -137.91 -222.267 -191.761C-177.96 -245.786 -96.6962 -265.247 -27.1815 -293.202Z" fill="#EE7B30"/>
          </svg>
        </div>
        

      <div class="Login-wrapper">
        <form class="main-form" method="POST" action="{% url 'user:login' %}">
          {% csrf_token %}
          <div class="header-text">
                <h4>به پلاکارد خوش آمدید</h4>
                <div class="left-header">
                      <h5>حساب کاربری ندارید؟</h5>
                      <a href="{% url 'user:register' %}">ثبت نام کنید</a>
                </div>
            </div>
            
                <!-- {/* the login part */} -->
            <div class='text-part'> 
                <h1>ورود</h1>
                <label htmlFor="username">نام کاربری خود را وارد کنید</label>                       
                {{form.username}}
                    
                <label htmlFor="password">رمزعبور خود را وارد کنید</label>
                {{form.password}}

                <button id = "btn2" type="submit">ورود</button>
            </div>
        </form>
      </div>

    </body>

</html>

api/templates/UserProfile.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="{% static '/css/UserProfile.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@200&display=swap" rel="stylesheet">
  </head>
  <header>
    <!-- {/* the logo in header */} -->
    <div class="header_items">

    <!-- Placard logo from media folder -->
      <a href="{% url 'api:home' %}">
        <img class = "logo-img" src="{% static 'media/PlacardLogo.svg' %}" alt="Placard Logo" />
      </a>  

      <!-- Buttons and links to other pages from home page -->
      <button id="create_post_btn" onclick=""><a href="{% url 'api:create_post' user.id %}">ثبت آگهی</a></button>
     
      <button id="header-profile-btn" onclick="">
        <h4>پلاکارد من</h4>
        <img src="{% static 'media/ProfilePic.png' %}" class="header-profilepic"/>
        <div class="sub-menu-wrap">
          <div class="sub-menu">
            <ul>
              <li>
                <h3>{{user.username}}</h3>
                <hr>
              </li>
              <li>
                <a href="{% url 'user:user_profile' %}" class="sub-menu-link">
                  <img src="{% static 'media/account.png' %}"/>
                  <p>پروفایل</p>
                </a>
              </li>
              <li>
                <a href="{% url 'user:logout' %}" class="sub-menu-link">
                  <img src="{% static 'media/logout.png' %}" />
                  <p>خروج</p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </button>
     </div>  

    </div>
    <br>
    <br>
  </header>

    <body>
      <!-- User Profile -->
      <div class="profile-wrapper">
        <div class="BG-color">
            <h1 id="username">{{user.username}}</h1>
        </div>

        <div class="user-img">
            <img src="{% static 'media/account.png' %}" alt="user profile picture"/>
        </div>

        <h3>:آگهی‌های منتشر شده</h3>
        <!-- post appearance for lists of posts uploaded by user-->
        <div class="post-container">
          {% for post in posts %}
            {% if post.post_type == 'StudyBuddy' %}
              <div class="post-design-sb">
                <div class="post-info">
                  <div class="post-edit">
                    <button onclick=""><a href="{% url 'api:delete_post' post.id %}">حذف آگهی</a></button>
                  </div>
                  <a id="title" href="{% url 'api:post_detail' post.id %}"> {{post.title|truncatechars:10}} </a>
                </div>
                <div class="post-img">
                  <img src="{% static 'media/nopicture.png' %}" alt="post picture"/>
                </div>
              </div>
            {% else %}
              <div class="post-design">
                <div class="post-info">
                  <div class="post-edit">
                    <button onclick=""><a href="{% url 'api:delete_post' post.id %}">حذف آگهی</a></button>
                  </div>
                  <a id="title" href="{% url 'api:post_detail' post.id %}"> {{post.title|truncatechars:10}} </a>
                </div>
                <div class="post-img">
                  <img src="{% static 'media/nopicture.png' %}" alt="post picture"/>
                </div>
              </div>
            {% endif %}
            
            {% if forloop.counter|divisibleby:"3" %}
              <br />
            {% endif %}
    
            {% endfor %}
        </div>     

      </div>

    </body>

</html>

api/templates/postVisibility.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="{% static '/css/postVisibility.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@200&display=swap" rel="stylesheet">
  </head>
  <header>
    <!-- {/* the logo in header */} -->
    <div class="header_items">

    <!-- Placard logo from media folder -->
      <a href="{% url 'api:home' %}">
        <img class = "logo-img" src="{% static 'media/PlacardLogo.svg' %}" alt="Placard Logo" />
      </a>  

      <!-- Buttons and links to other pages from home page -->
      <button id="create_post_btn" onclick=""><a href="{% url 'api:create_post' user.id %}">ثبت آگهی</a></button>
     
      <button id="header-profile-btn" onclick="">
        <h4>پلاکارد من</h4>
        <img src="{% static 'media/ProfilePic.png' %}" class="header-profilepic"/>
        <div class="sub-menu-wrap">
          <div class="sub-menu">
            <ul>
              <li>
                <h3>{{user.username}}</h3>
                <hr>
              </li>
              <li>
                <a href="{% url 'user:user_profile' %}" class="sub-menu-link">
                  <img src="{% static 'media/account.png' %}"/>
                  <p>پروفایل</p>
                </a>
              </li>
              <li>
                <a href="{% url 'user:logout' %}" class="sub-menu-link">
                  <img src="{% static 'media/logout.png' %}" />
                  <p>خروج</p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </button>
     </div>  

    </div>
    <br>
    <br>
  </header>
    <body>

    <!-- Background blobs  -->
    <!-- <img src="{% static 'media/pic.jpg' %}" id="BG-img"/> -->

    {% if post.post_type == 'StudyBuddy' %}
      <div class="post-wraper-sb">
        <div class="post-img">
            <img src="{% static 'media/nopicture.png' %}" />
        </div>
        <div class="post-info">
            <div class="post-title">
                <h1 id="title">{{post.title}}</h1>
                <h5 id="time">{{post.get_date}}</h5>
            </div>
            <div class="post-detail">
                <div class="post-quality">
                    <h3>نوع آگهی</h3>
                    <h4>{{post.get_post_type_display}}</h4>
                </div>
                
                {% if post.get_post_type_display == "خرید و فروش" %}
                <hr id ="hr-1">
                  <div class="post-price">
                    <h3>قیمت</h3>
                    <h4>
                      {% if post.price == 0 %}
                        رایگان
                      {% else %}
                        {{post.get_price}} تومان 
                      {% endif %}
                    </h4>
                  </div>
                {% endif %}
                
                <hr id="hr-2">
                <div class="contact-info">
                  <h3>راه ارتباطی</h3>
                  <h4>{{post.contact_info}}</h4>
                </div>
                <hr id="hr-3"/>
                <div class="post-description">
                    <h3>توضیحات</h3>
                    <p id = "description">{{post.description}}</p>
                </div>
                
            </div>
        </div>
    </div>
    {% else %}
      <div class="post-wraper">
        <div class="post-img">
            <img src="{% static 'media/nopicture.png' %}" />
        </div>
        <div class="post-info">
            <div class="post-title">
                <h1 id="title">{{post.title}}</h1>
                <h5 id="time">{{post.get_date}}</h5>
            </div>
            <div class="post-detail">
                <div class="post-quality">
                    <h3>نوع آگهی</h3>
                    <h4>{{post.get_post_type_display}}</h4>
                </div>
                
                {% if post.get_post_type_display == "خرید و فروش" %}
                <hr id ="hr-1">
                  <div class="post-price">
                    <h3>قیمت</h3>
                    <h4>
                      {% if post.price == 0 %}
                        رایگان
                      {% else %}
                        {{post.get_price}} تومان 
                      {% endif %}
                    </h4>
                  </div>
                {% endif %}
                
                <hr id="hr-2">
                <div class="contact-info">
                  <h3>راه ارتباطی</h3>
                  <h4>{{post.contact_info}}</h4>
                </div>
                <hr id="hr-3"/>
                <div class="post-description">
                    <h3>توضیحات</h3>
                    <p id = "description">{{post.description}}</p>
                </div>
                
            </div>
        </div>
    </div>
    {% endif %}


    </body>

</html>